# Generated by Django 6.0.6 on 2026-06-20 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок группы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа документов',
                'verbose_name_plural': 'Группы документов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='URL')),
                ('key', models.CharField(choices=[('home', 'Главная'), ('about', 'О нас'), ('services', 'Услуги'), ('docs', 'Образцы документов'), ('prices', 'Цены'), ('contacts', 'Контакты')], max_length=50, unique=True, verbose_name='Ключ')),
                ('dropdown', models.CharField(blank=True, choices=[('', 'Нет'), ('services', 'Услуги'), ('docs', 'Образцы документов')], max_length=20, verbose_name='Дропдаун')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='URL (slug)')),
                ('nav_key', models.CharField(blank=True, choices=[('home', 'Главная'), ('about', 'О нас'), ('services', 'Услуги'), ('docs', 'Образцы документов'), ('prices', 'Цены'), ('contacts', 'Контакты')], max_length=50, verbose_name='Ключ меню')),
                ('meta_title', models.CharField(blank=True, max_length=300, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('content', models.TextField(blank=True, verbose_name='Контент (HTML)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга (дропдаун)',
                'verbose_name_plural': 'Услуги (дропдаун)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='Остались вопросы?', max_length=200, verbose_name='Текст вопроса')),
                ('question_link_text', models.CharField(default='ЖМИ СЮДА!', max_length=100, verbose_name='Текст ссылки')),
                ('question_link_url', models.CharField(default='/contacts/', max_length=200, verbose_name='URL ссылки')),
                ('working_hours', models.CharField(default='Пн–Сб 9:00–21:00 · Вс выходной', max_length=200, verbose_name='Режим работы')),
                ('phone', models.CharField(default='+375 29 689-60-66', max_length=50, verbose_name='Телефон (основной)')),
                ('phone_mts', models.CharField(default='+375 33 681-60-66', max_length=50, verbose_name='Телефон MTS')),
                ('email', models.EmailField(default='6896066@tut.by', max_length=254, verbose_name='Email')),
                ('logo_letter', models.CharField(default='А', max_length=5, verbose_name='Буква логотипа')),
                ('logo_name', models.CharField(default='АТТЕСТАЦИЯ РМ', max_length=100, verbose_name='Название компании')),
                ('logo_subtitle', models.CharField(default='МИНСК · БЕЛАРУСЬ', max_length=100, verbose_name='Подпись логотипа')),
                ('cta_text', models.CharField(default='Оставить заявку', max_length=100, verbose_name='Текст кнопки')),
                ('cta_url', models.CharField(default='/contacts/', max_length=200, verbose_name='URL кнопки')),
                ('tagline', models.CharField(default='Качество и оперативность — это наша главная задача!', max_length=300, verbose_name='Слоган в подвале')),
                ('copyright', models.CharField(default='© 2026 Аттестация рабочих мест в Беларуси и Минске. Все права защищены.', max_length=300, verbose_name='Копирайт')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='DocLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.docgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Ссылка на документ',
                'verbose_name_plural': 'Ссылки на документы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.CharField(default='#', max_length=500, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerlink_set', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['order'],
            },
        ),
    ]
