# Generated by Django 6.0.3 on 2026-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mega_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.SlugField(blank=True, help_text='Slug категории-агрегатора, которой принадлежит страница (напр. «articles», «docs»). Оставьте пустым, если страница не входит в категорию.', max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='page',
            name='summary',
            field=models.TextField(blank=True, help_text='Короткий текст для карточки на странице категории. Если пусто — берётся первый абзац контента.', verbose_name='Анонс'),
        ),
    ]
