# Generated by Django 6.0.6 on 2026-06-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenuColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(choices=[('services', 'Мегаменю: Услуги'), ('docs', 'Мегаменю: Образцы документов')], default='docs', max_length=20, verbose_name='Панель')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок колонки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Колонка мегаменю',
                'verbose_name_plural': 'Колонки мегаменю',
                'ordering': ['panel', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MegaMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.CharField(blank=True, help_text='Показывается под названием (только для колонки «Услуги»)', max_length=300, verbose_name='Короткое описание')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.megamenucolumn', verbose_name='Колонка')),
            ],
            options={
                'verbose_name': 'Ссылка мегаменю',
                'verbose_name_plural': 'Ссылки мегаменю',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('url', models.CharField(blank=True, help_text='Оставьте пустым, если пункт открывает мегаменю', max_length=500, verbose_name='URL')),
                ('dropdown', models.CharField(blank=True, choices=[('', 'Обычная ссылка'), ('services', 'Мегаменю: Услуги'), ('docs', 'Мегаменю: Образцы документов')], default='', max_length=20, verbose_name='Тип мегаменю')),
                ('active_key', models.SlugField(blank=True, help_text='Slug, по которому подсвечивается активный пункт (напр. «docs», «about»)', verbose_name='Ключ активности')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Главное меню',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='doclink',
            name='group',
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
        migrations.DeleteModel(
            name='ServiceItem',
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='nav_key',
        ),
        migrations.AddField(
            model_name='page',
            name='active_key',
            field=models.SlugField(blank=True, help_text='Ключ активности для подсветки пункта меню (напр. «docs», «about»)', verbose_name='Ключ меню'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменена'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO-описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(help_text='Часть URL после домена, без слэшей. Например: contacts или obrazets-prikaza-o-provedenii-...', max_length=500, unique=True, verbose_name='URL (slug)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_text',
            field=models.CharField(default='Оставить заявку', max_length=100, verbose_name='Текст кнопки CTA'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_url',
            field=models.CharField(default='/contacts/', max_length=200, verbose_name='URL кнопки CTA'),
        ),
        migrations.DeleteModel(
            name='DocGroup',
        ),
        migrations.DeleteModel(
            name='DocLink',
        ),
    ]
