#
# Nginx custom snippet for attestation.by.
# Подключить в CWP → nginx конфиг сайта.
#

location /static/ {
    alias /home/django/webapps/attestation/staticfiles/;
    access_log off;
    expires 30d;
    add_header Cache-Control "public";
}

location /media/ {
    alias /home/django/webapps/attestation/media/;
    access_log off;
    expires 30d;
    add_header Cache-Control "public";
}
